spring:
  application:
    name: yupao_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao
    username: yupao
    password: xxxxxx
    # session 失效时间 （1天）
  session:
    timeout: 86400
  redis:
    host: localhost
    port: 6379
    database: 0
    password: xxxxx
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: friend.huifly.cn


